---
- hosts: all
  gather_facts: false
  connection: local
  user: remote
  sudo: false

  vars:
    vcenter_hostname: '10.4.4.23'
    datacenter: 'RedHat-CLS'
    esxi_host: '10.4.4.20'
    notes: 'Created by Ansible and CloudForms'
    disk: '10'
    datastore: 'zfs7420-ds'
    network: 'PH-Network'
    memory: '256'
    cpucount: '1'
    osid: 'rhel7_64Guest'

  tasks:
    - name: Create Virtual Machines
      vsphere_guest:
        validate_certs: no
        vcenter_hostname: "{{ vcenter_hostname }}"
        guest: "{{ inventory_hostname }}"
        state: present
        vm_extra_config:
          notes: "{{ notes }}"
        vm_disk:
          disk1:
            size_gb: "{{ disk }}"
            type: thin
            datastore: "{{ datastore }}"
        vm_nic:
          nic1:
            type: vmxnet3
            network: "{{ network }}"
            network_type: standard
        vm_hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpucount }}"
          osid: "{{ osid }}"
          scsi: paravirtual
        esxi:
          datacenter: "{{ datacenter }}"
          hostname: "{{ esxi_host }}"
